---------------------------------------------------------------------------------------------
--' Для того, что бы мир не был загружен кучей трупов,
--' будем их потихоньку удалять.
--' Made by Distemper ----------------------------------------------------------------
--' 11.02.08 ----------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
local function add_to_release_table(release_tbl, object_id)
	printf("add to release_objects_table ["..object_id.."]")
	local obj_params = {}
	obj_params.id = object_id
	obj_params.death_time = time_global()
	table.insert(release_tbl, obj_params)
end

local RB_manager = nil

class "Crelease_body"

function Crelease_body:__init()
	self.release_objects_table = {} -- таблица "СТЕК" трупов
	self.keep_items_table = {} -- таблица квестовых предметов	self.current_object_id = 0 -- id только что убитого npc
	--' Итерируемся по списку квестовых итемов.
	local snd_ini = ini_file("misc\\death_generic.ltx")
	if not snd_ini:section_exist("keep_items") then
		abort("There is no section [keep_items] in death_generic.ltx")
	end
	local n = snd_ini:line_count("keep_items")
	local value = ""
	for i = 0, n - 1 do
		result, section, value  = snd_ini:r_line("keep_items", i, "", "")
		table.insert(self.keep_items_table, section)
	end
	
	--clp
	self.bodyKeepDuration = 20 * 60 * 1000
end


--clp
function Crelease_body:moving_dead_body(obj)
	local object_id = obj:id()
	if self:inspection_result(obj) then
		add_to_release_table(self.release_objects_table, object_id)
		self:try_to_release()
	end
end
function Crelease_body:try_to_release()
	local function getDeathDuration( info )
		return math.abs( time_global() - info.death_time )
	end
	local function compareDeathTime( a, b )
		return getDeathDuration( a ) > getDeathDuration( b )
	end
	table.sort( self.release_objects_table, compareDeathTime )
	
	while #self.release_objects_table > 0 do
		local info = self.release_objects_table[ 1 ]
		local object = alife():object( info.id )
		if getDeathDuration( info ) > self.bodyKeepDuration and
			bind_stalker.delayed_alife_release_objects[ info.id ] == nil then
			if object then
				alife():release( object, true )
			end
			table.remove( self.release_objects_table, 1 )
		else
			break
		end
	end
end
--clp

function Crelease_body:inspection_result(obj)
	for k,v in pairs(self.keep_items_table) do
		if obj:object(self.keep_items_table[k]) ~= nil then
			printf("Object << "..obj:name().." >> presence_in_keep_items_table") -- в инвентаре есть квестовый предмет
			return false
		end
	end
	if obj:character_community() == "arena_enemy" then
		printf("Object << "..obj:name().." >> presence_in_survival_zone") -- надидится в "Арене"
		return false
	end
	if obj:story_id() < 65535 then
		printf("Object << "..obj:name().." >> presence_in_story") -- помечен как сюжетный
		return false
	end
	if self:check_for_known_info(obj) then
		printf("Object << "..obj:name().." >> presence_in_known_info")
		return false
	end
	return true
end

function  Crelease_body:check_for_known_info(obj)
	local char_ini = ""
	local spawn_ini = obj:spawn_ini()
	local filename = nil
	if spawn_ini then
		filename = utils.cfg_get_string(spawn_ini, "logic", "cfg", obj, false, "")
		printf("filename is [%s]", tostring(filename))
	end
	if filename ~= nil then
		char_ini = ini_file(filename)
	else
		char_ini = obj:spawn_ini() or ini_file("scripts\\dummy.ltx")
	end
	local st = db.storage[obj:id()]
	local known_info = utils.cfg_get_string(char_ini, st.section_logic, "known_info", obj, false, "", nil) or "known_info"
	if char_ini:section_exist(known_info) then
		return true
	end
	return false
end

function Crelease_body:save(packet)
	set_save_marker(packet, "save", false, "Crelease_body")
	local count = #self.release_objects_table
	packet:w_u16(count)
	for k,v in pairs(self.release_objects_table) do
		packet:w_u16(v.id)
		packet:w_u16(v.death_time)
	end
	local level_id = game_graph():vertex(alife():object(0).m_game_vertex_id):level_id()
	packet:w_u16(level_id)
	set_save_marker(packet, "save", true, "Crelease_body")
end

function Crelease_body:load(reader)
	set_save_marker(reader, "load", false, "Crelease_body")
	local count = reader:r_u16()
	self.release_objects_table = {}
	for i = 1, count do
		local vid = reader:r_u16()
		local dt = reader:r_u16()
		table.insert( self.release_objects_table, { id = vid, death_time = dt } )
	end
	local level_id = reader:r_u16()
	set_save_marker(reader, "load", true, "Crelease_body")
end

function get_release_body_manager()
	if(RB_manager==nil) then
				RB_manager = Crelease_body()
		end
		return RB_manager
end
