
local item_by_chance = {}
local mul_by_item = {}
local count_by_item = {}
local items_by_type = {}

local stash_ini = ini_file("misc\\ps_stash_items_generic.ltx")

function init_stash_settings()
	if stash_ini:section_exist("default") then
		local n = stash_ini:line_count("default")
		error_log("reading "..n.." sections for ps_stashes: default")
		local id, value = "", ""
		for i=0,n-1 do
			result, id, value = stash_ini:r_line("default",i,"","")
			item_by_chance[id] = 100*tonumber(value)
		end
	end
	
	local item_types = {"artifact", "ammo", "weapons", "suits", "medicals", "food", "misc", "flash_drives"}
	for k,v in pairs(item_types) do
		items_by_type[v] = {}
		if stash_ini:section_exist(v) then
			local n = stash_ini:line_count(v)
			error_log("reading "..n.." sections for ps_stashes: "..v)
			local id, value = "", ""
			for i=0,n-1 do
				result, id, value = stash_ini:r_line(v,i,"","")
				items_by_type[v][id] = tostring(id)
			end
		end
	end

	local item_count_section = "item_counts" 
	local n = stash_ini:line_count(item_count_section)
	error_log("reading "..n.." sections for ps_stashes: item_counts")
	for i=0,n-1 do
		result, id, value = stash_ini:r_line(item_count_section,i,"","")
		local t = parse_nums(value)
		if t[1] == nil then
			abort("Error on [stash_ini] declaration. Section [%s], line [%s]", item_count_section, tostring(id))
		end
		local min = t[1]
		local max = t[2]
		if max == nil then
			max = min
		end
		count_by_item[id] = {min = min, max = max}
	end
end

function spawn_loot()
	local content = ""
	local counts = {artifact = 1, ammo = 3, weapons = 1, suits = 1, medicals = 3, food = 3, misc = 2, flash_drives = 1}
	local spawn_items = item_by_chance
    local number = 1
	local item_no = 0
	local item_name = ""
	local n = 0
    if spawn_items == nil then
    	return ""
    end
	for k,v in pairs(items_by_type) do
		local stash_size = 0
		for kk,vv in pairs(v) do
			stash_size = stash_size + 1
		end
		error_log(k.." "..stash_size)
		if stash_size ~= 0 then
			for i=1,counts[k] do
				item_no = math.random(stash_size)
				n = 0
				for kk,vv in pairs(v) do
					n = n + 1
					if n == item_no then
						item_name = kk
					end
				end
				error_log(tostring(item_no).." "..item_name)
				if math.random(100) <= spawn_items[item_name] then
					number = math.ceil(math.random(count_by_item[item_name].min, count_by_item[item_name].max))
					if content == "" then
						content = content..tostring(item_name)..", "..tostring(number)
					else
						content = content..", "..tostring(item_name)..", "..tostring(number)
					end
				end
			end
		end
	end
	if content == "" then
		content = spawn_loot()
	end
	return content
end

----------------------------------------------------------------------
local locked_treasures = {}

function save(packet)
	set_save_marker(packet, "save", false, "PSRandomTreasures")
	local n = 0
	for k,v in pairs(locked_treasures) do
		n = n + 1
	end
	packet:w_u16(n)
	for k,v in pairs(locked_treasures) do
		packet:w_stringZ(k)
		utils.w_CTime(packet, v)
	end
	set_save_marker(packet, "save", true, "PSRandomTreasures")
end

function load(reader)
	set_save_marker(reader, "load", false, "PSRandomTreasures")
	local n = reader:r_u16()
	locked_treasures = {}
	for i=1,n do
		id = reader:r_stringZ()
		time = utils.r_CTime(reader)
		locked_treasures[id] = time
	end
	set_save_marker(reader, "load", true, "PSRandomTreasures")
end

function is_treasure_unlocked(section_name)
	treasure_time = locked_treasures[section_name]
	local time = game.get_game_time()
	if treasure_time ~= nil then
		if math.floor(time:diffSec(treasure_time)) > 172800 then	-- 60x60x24x2 - 2 days ingame
			return true
		end
	else
		return true
	end
	return false
end

function unlock_treasure(section_name)
	if is_treasure_unlocked(section_name) == true then
		local count = 1
		for k,v in pairs(locked_treasures) do
			if section_name == k then
				table.remove(locked_treasures, count)
				break
			end
			count = count + 1
		end
	end
end

function is_treasure_available(section_name)
	if is_treasure_unlocked(section_name) == true then
		unlock_treasure(section_name)
		return true
	end
	return false
end

function lock_treasure(section_name)
	local time = game.get_game_time()
	locked_treasures[section_name] = time
end


