----------------------------------------------------------------------------------------------------------------------
--	Выдача информации сталкерам.
--	автор: Диденко Руслан (Stohe)
--	TODO:
----------------------------------------------------------------------------------------------------------------------

local info_by_community = {
	stalker =  {"stalker_novice_1",
				"stalker_novice_2",
				"stalker_stalker_1",
				"stalker_stalker_2",
				"stalker_veteran_1",
				"stalker_veteran_2",
				"faction_bandit",
				"faction_stalker",
				"faction_army",
				"faction_merc",
				"faction_monolith",
				"faction_zombie",
				"mutant_dog",
				"mutant_boar",
				"mutant_flesh",
				"mutant_tushkano",
				"mutant_cat",
				"mutant_snork",
				"mutant_pseudodog",
				"mutant_bloodsucker",
				"mutant_psy_dog",
				},

	monolith = {"monolith_novice_1",
				"monolith_stalker_1",
				"monolith_stalker_2",
				"monolith_veteran_1",
				},

	army = {"army_novice_1",
			"army_stalker_1",
			"army_veteran_1",
			"faction_stalker",
			"faction_merc",
			"faction_monolith",
			"faction_zombie",
			"mutant_dog",
			"mutant_boar",
			"mutant_flesh",
			"mutant_tushkano",
			"mutant_snork",
			},

	killer =   {},

	ecolog =   {"faction_zombie",
				"mutant_dog",
				"mutant_boar",
				"mutant_flesh",
				"mutant_tushkano",
				"mutant_cat",
				"mutant_snork",
				"mutant_pseudodog",
				"mutant_bloodsucker",
				"mutant_psy_dog",
				"mutant_controller",
				"mutant_pseudogiant",
				"mutant_chimera",
				},

	dolg = {"dolg_novice_1",
			"dolg_novice_2",
			"dolg_novice_3",
			"dolg_stalker_1",
			"dolg_stalker_2",
			"dolg_stalker_3",
			"dolg_stalker_4",
			"dolg_stalker_5",
			"dolg_stalker_6",
			"dolg_veteran_1",
			"dolg_veteran_2",
			"dolg_veteran_3",
			"dolg_master_1",
			"faction_bandit",
			"faction_stalker",
			"faction_army",
			"faction_merc",
			"faction_monolith",
			"faction_zombie",
			"mutant_dog",
			"mutant_boar",
			"mutant_flesh",
			"mutant_tushkano",
			"mutant_cat",
			"mutant_snork",
			"mutant_pseudodog",
			"mutant_bloodsucker",
			"mutant_psy_dog",
			"mutant_controller",
			"mutant_pseudogiant",
			"mutant_chimera",
			},

	freedom =  {"freedom_novice_1",
				"freedom_stalker_1",
				"freedom_stalker_2",
				"freedom_stalker_3",
				"freedom_veteran_1",
				"faction_bandit",
				"faction_stalker",
				"faction_army",
				"faction_merc",
				"faction_monolith",
				"faction_zombie",
				"mutant_dog",
				"mutant_boar",
				"mutant_flesh",
				"mutant_tushkano",
				"mutant_cat",
				"mutant_snork",
				"mutant_pseudodog",
				"mutant_bloodsucker",
				"mutant_psy_dog",
				},

	bandit =   {"bandit_novice_1",
				"bandit_stalker_1",
				"bandit_veteran_1",
				"faction_stalker",
				"faction_army",
				"faction_merc",
				"faction_zombie",
				"mutant_dog",
				"mutant_boar",
				"mutant_flesh",
				"mutant_tushkano",
				"mutant_cat",
				"mutant_snork",
				"mutant_pseudodog",
				},

	renegade = {"faction_bandit",
				"faction_stalker",
				"faction_army",
				"faction_merc",
				"faction_monolith",
				"faction_zombie",
				"mutant_dog",
				"mutant_boar",
				"mutant_flesh",
				"mutant_tushkano",
				"mutant_cat",
				"mutant_snork",
				"mutant_pseudodog",
				},
				
	}

local info_by_rank = {
	novice =   {"stalker_novice_1",
				"stalker_novice_2",
				"monolith_novice_1",
				"army_novice_1",
				"bandit_novice_1",
				"freedom_novice_1",
				"dolg_novice_1",
				"dolg_novice_2",
				"dolg_novice_3",
				"faction_bandit",
				"faction_stalker",
				"faction_army",
				"mutant_dog",
				"mutant_boar",
				"mutant_flesh",
				"mutant_tushkano",
				},

	experienced =  {"stalker_stalker_1",
					"stalker_stalker_2",
					"monolith_stalker_1",
					"monolith_stalker_2",
					"army_stalker_1",
					"bandit_stalker_1",
					"freedom_stalker_1",
					"freedom_stalker_2",
					"freedom_stalker_3",
					"dolg_stalker_1",
					"dolg_stalker_2",
					"dolg_stalker_3",
					"dolg_stalker_4",
					"dolg_stalker_5",
					"dolg_stalker_6",
					"faction_bandit",
					"faction_stalker",
					"faction_army",
					"faction_merc",
					"faction_monolith",
					"faction_zombie",
					"mutant_cat",
					"mutant_snork",
					"mutant_pseudodog",
					},

	veteran =  {"stalker_veteran_1",
				"stalker_veteran_2",
				"monolith_veteran_1",
				"army_veteran_1",
				"bandit_veteran_1",
				"freedom_veteran_1",
				"dolg_veteran_1",
				"dolg_veteran_2",
				"dolg_veteran_3",
				"faction_bandit",
				"faction_stalker",
				"faction_army",
				"faction_merc",
				"faction_monolith",
				"faction_zombie",
				"mutant_bloodsucker",
				"mutant_psy_dog",
				},

	master =   {"dolg_master_1",
				"faction_bandit",
				"faction_stalker",
				"faction_army",
				"faction_merc",
				"faction_monolith",
				"faction_zombie",
				"mutant_controller",
				"mutant_pseudogiant",
				"mutant_chimera",
				}
}


function loadInfo(npc, char_ini, known_info)
	-- Загрузка из кастом даты
	local known_info = known_info or "known_info"
	if char_ini:section_exist(known_info) then
		printf("Known info section exists [%s]", npc:name())
		local n = char_ini:line_count(known_info)
		local result, id, value = 0,"",""

		for i=0,n-1 do
			result, id, value = char_ini:r_line(known_info,i,"","")
			printf("info --> npc [%s]", id)
			give_npc_info(npc, id)
		end
	end

	-- Загрузка из генератора.
	local community_info = info_by_community[npc:character_community()]
	if community_info == nil then
		return
	end

	local rank = ranks.get_obj_rank_name(npc)
	local rank_info = info_by_rank[rank]
	if rank_info == nil then
		return
	end

	local tt = {}
	-- оставляем инфопоршны, которые есть и там и там.
	for k,v in pairs(community_info) do
		for kk,vv in pairs(rank_info) do
			if v == vv then
				-- Добавляем в список доступных знаний
				table.insert(tt, v)
				break
			end
		end
	end

	local size = #tt
	for k = 1,math.min(size,3) do
		if math.random(100) >= 80 then
			local ii = tt[math.random(size)]
			give_npc_info(npc, ii)
		end
	end
end

function give_npc_info(npc, info)
	-- Даем НПС инфопоршны
	npc:give_info_portion(info)

	-- Проверяем есть ли озвученная история на этот инфопоршн, и если есть
	-- добавляем ее тоже
	if sound_theme.theme[info] ~= nil then
		if db.story_by_id[npc:id()] == nil then
			db.story_by_id[npc:id()] = {}
		end

		table.insert(db.story_by_id[npc:id()], info)
	end
end